import sys, csv, io, codecs, string, re

#Encodes in UTF-8, removing any special characters
sys.stdout = io.TextIOWrapper(sys.stdout.detach(), encoding = 'utf-8')
sys.stderr = io.TextIOWrapper(sys.stderr.detach(), encoding = 'utf-8')
if sys.stdout.encoding != 'UTF-8':
    sys.stdout = codecs.getwriter('utf-8')(sys.stdout.buffer, 'strict')
if sys.stderr.encoding != 'UTF-8':
    sys.stderr = codecs.getwriter('utf-8')(sys.stderr.buffer, 'strict')

#We do not care about any characters other than alphabetic characters or spaces, so we remove numbers and any special characters
regex = re.compile('[^a-zA-Z ]')

#Opens the file we write to, then the file we read from
with open('recipesparsed.txt', 'w') as f2:
	with open ('recipes.csv', mode='r', encoding='utf-8') as infile:
		reader = csv.reader(infile)
		for row in reader:
#All members of the csv file are enclosed in quotation marks - this line removes the quotation marks and stores the values in the variable lis
			lis = ["'{}'".format(row[1]) for row[1] in row[1].split("'") if row[1] not in ("", ", ")]
			for x in range(len(lis)):
#This code is what takes in lis and gets rid of any non alphabetic character
				y = regex.sub('', lis[x])
				y = y.lower()
				if y != '':
					y = y.replace(" cup", "")
					y = y.replace(" tablespoons", "")
					y = y.replace(" tablespoon", "")
					y = y.replace(" teaspoons", "")
					y = y.replace(" teaspoon", "")
					y = y.replace(" cups", "")
					y = y.replace(" cup", "")
					y = y.replace(" ounces", "")
					y = y.replace(" ounce", "")
					y = y.replace("hidden valley original", "")
					y = y.replace(" divided", "")
					y = y.replace("smithfield", "")
					y = y.replace("fresh", "")
					y = y.replace(" chopped", "")
					y = y.replace(" diced", "")
					y = y.replace(" optional", "")
					y = y.replace(" removed", "")
					y = y.replace("extra", "")
					y = y.replace("tender ", "")
					y = y.replace("st louis", "")
					y = y.replace(" a ", " ")
					y = y.replace(" in ", " ")
					y = y.replace("softened", "")
					y = y.replace("thawed", "")
					y = y.replace("to ", " ")
					y = y.replace("melted", "")
					y = y.replace("toasted", "")
					y = y.replace("taste", "")
					y = y.replace("dove ", "")
					y = y.replace("brand ", "")
					y = y.replace(" or ", " ")
					y = y.replace(" as ", " ")
					y = y.replace("needed", "")
					y = y.replace("such ", " ")
					y = y.replace("more", " ")
					y = y.replace("taste", " ")
					y = y.replace("nestle ", "")
					y = y.replace("toll house ", "")
					y = y.replace("honey maid ", "")
					y = y.replace("philadelphia ", "")
					y = y.replace("cool whip ", "")
					y = y.replace("lite ", "")
					y = y.replace("freshly", "")
					y = y.replace("fresh", "")
					y = y.replace(" few ", "")
					y = y.replace(" inches", "")
					y = y.replace(" inch", "")
					y = y.replace(" about", "")
					y = y.replace(" in ", " ")
					y = y.replace(" and ", " ")
					y = y.replace(" for ", " ")
					y = y.replace(" another", "")
					y = y.replace(" handful", "")
					y = y.replace(" handfuls", "")
					y = y.replace(" of ", " ")
					y = y.replace(" pound", "")
					y = y.replace(" pounds", "")
					y = y.replace(" slice", "")
					y = y.replace(" slices", "")
					y = y.replace(" small", "")
					y = y.replace(" shredded", "")
					y = y.replace(" serving", "")
					y = y.replace(" cut ", "")
					y = y.replace(" preferably", "")
					y = y.replace(" trimmed", "")
					y = y.replace(" grated", "")
					y = y.replace(" halves", "")
					y = y.replace(" thirds", "")
					y = y.replace(" plus ", " ")
					y = y.replace(" oz ", " ")
					y = y.replace(" medium", "")
					y = y.replace("monterey jack ", "")
					y = y.replace(" s ", "")
					y = y.replace("  ", " ")
					y = y.replace("  ", " ")
					y = y.replace("  ", " ")
					y = y.replace("  ", " ")
					y = y.replace("  ", " ")
					y = y.replace("  ", " ")
					f2.write(y)
					f2.write("\n")